# [作業目標]

1. [簡答題] 請問下列兩種將 Array 轉換成 List 的方式有何不同？

```
print('list(a): ', list(a))
print('tolist(): ', a.tolist())
```

2. 請試著在程式中印出以下三個 NdArray 的屬性？（屬性：ndim、shape、size、dtype、itemsize、length、type）

```
a = np.random.randint(10, size=6) 
b = np.random.randint(10, size=(3,4)) 
c = np.random.randint(10, size=(2,3,2)) 
```

3. 如何利用 list(...) 實現 a.tolist() 的效果？試著用程式實作。


# 作業 

### 1. [簡答題] 請問下列兩種將 Array 轉換成 List 的方式有何不同？

```
print('list(a): ', list(a))
print('tolist(): ', a.tolist())
```


In [1]:
import numpy as np

a=np.random.randint(10,size=6)  #list(a)直接轉換成list，在一維下轉換效果相等
print('list(a):', list(a))
print('tolist():', a.tolist())

b=np.random.randint(10,size=6).reshape(2,3)
print('list(b):', list(b))  #在二維以後list(b)只會達到第一層轉換的效果，tolist()才能達成多層的型態轉換
print('tolist():', b.tolist())



list(a): [5, 4, 9, 6, 3, 4]
tolist(): [5, 4, 9, 6, 3, 4]
list(b): [array([4, 4, 3]), array([4, 8, 4])]
tolist(): [[4, 4, 3], [4, 8, 4]]


### 2. 請試著在程式中印出以下三個 NdArray 的屬性並且解釋結果？（屬性：ndim、shape、size、dtype、itemsize、length、type）

```
a = np.random.randint(10, size=6) 
b = np.random.randint(10, size=(3,4)) 
c = np.random.randint(10, size=(2,3,2)) 
```

In [ ]:
# 記得先 Import 正確的套件

import numpy as np

In [3]:

a = np.random.randint(10, size=6) 

print(a)

print(a.ndim) "只有一個維度"
print(a.shape) "每個維度只有6個元素"
print(a.size) "陣列當中有6個元素"
print(a.dtype) "資料型態為int32"
print(a.itemsize) "陣列中每個元素佔用的空間為4"
print(len(a)) "陣列的長度為6" #len屬於python的屬性而非numpy 
print(type(a)) "陣列類型numpy.ndarray" #type屬於python的屬性而非numpy

[3 9 8 5 3 0]
1
(6,)
6
int32
4
6
<class 'numpy.ndarray'>


In [4]:
b = np.random.randint(10, size=(3,4)) 

print(b)

print(b.ndim) "有兩個維度"
print(b.shape) "每個維度中有4個元素"
print(b.size) "陣列當中有12個元素"
print(b.dtype) "資料型態為int32"
print(b.itemsize) "陣列中每個元素佔用的空間為4"
print(len(b)) "陣列的長度為3" #len屬於python的屬性而非numpy 
print(type(b)) "陣列類型numpy.ndarray" #type屬於python的屬性而非numpy

[[3 4 5 5]
 [1 6 4 4]
 [2 9 9 0]]
2
(3, 4)
12
int32
4
3
<class 'numpy.ndarray'>


In [5]:
c = np.random.randint(10, size=(2,3,2)) 

print(c)

print(c.ndim) "有三個維度"
print(c.shape) "每一個維度中有2個元素"
print(c.size) "陣列當中有12個元素"
print(c.dtype) "資料型態為int32"
print(c.itemsize) "陣列當中每個元素佔用的空間為4"
print(len(c)) "陣列的長度為2"  #len屬於python的屬性而非numpy 
print(type(c)) "陣列類型numpy.ndarray" #type屬於python的屬性而非numpy

[[[0 1]
  [7 2]
  [2 3]]

 [[1 9]
  [2 5]
  [0 0]]]
3
(2, 3, 2)
12
int32
4
2
<class 'numpy.ndarray'>


### 3. 如何利用 list(...) 實現 a.tolist() 的效果？試著用程式實作。


In [ ]:
a = np.random.randint(10, size=6) 

print(a.tolist())
print(list(a))


[7, 6, 7, 3, 7, 5]
[7, 6, 7, 3, 7, 5]


In [ ]:
b = np.random.randint(10, size=(3,4)) 

print(b.tolist())
print(list(b))


[[5, 7, 4, 6], [9, 4, 0, 1], [9, 1, 2, 9]]
[array([5, 7, 4, 6]), array([9, 4, 0, 1]), array([9, 1, 2, 9])]


In [ ]:
c = np.random.randint(10, size=(2,3,2)) 

print(c.tolist())
print(list(c))


[[[0, 4], [0, 1], [9, 5]], [[8, 7], [8, 2], [6, 0]]]
[array([[0, 4],
       [0, 1],
       [9, 5]]), array([[8, 7],
       [8, 2],
       [6, 0]])]


In [6]:
#list(a) a.tolist()差別在於是否可以處理巢狀array
#所以要用list()處理就要使用迴圈的方式處理，利用遞迴將每一層的array轉換成list

def tolist(iterable):
    if type(iterable)!=np.ndarray:
        return iterable
    newlist=[]
    for obj in iterable:
        newlist.append(tolist(obj))
    return list(newlist)
    

print(tolist(a))
print(tolist(b))
print(tolist(c))

[3, 9, 8, 5, 3, 0]
[[3, 4, 5, 5], [1, 6, 4, 4], [2, 9, 9, 0]]
[[[0, 1], [7, 2], [2, 3]], [[1, 9], [2, 5], [0, 0]]]


In [9]:
#進階版寫法 使得程式碼看起來更乾淨

def tolist(iterable):
    if type(iterable)!= np.ndarray:
        return iterable
    return [tolist(obj) for obj in iterable]
    
print(tolist(a))
print(tolist(b))
print(tolist(c))

[3, 9, 8, 5, 3, 0]
[[3, 4, 5, 5], [1, 6, 4, 4], [2, 9, 9, 0]]
[[[0, 1], [7, 2], [2, 3]], [[1, 9], [2, 5], [0, 0]]]
